Add missing QTimer include to Qt client
Fixed compilation error C2027:
- Added #include <QTimer> to mainwindow.cpp
- QTimer::singleShot() was being used for auto-login delay